EX.06
USE MASTER
CREATE DATABASE MOTORISTA_VIAGEM
USE MOTORISTA_VIAGEM

CREATE TABLE MOTORISTA(
CODIGO				INT					NOT NULL,
NOME				VARCHAR(40)			NOT NULL,
DATN				DATE				NOT NULL,
NATURALIDADE		VARCHAR(40)			NOT NULL
PRIMARY KEY (CODIGO)
)
INSERT INTO MOTORISTA
VALUES
(12341,'Julio Cesar','1978-04-18','São Paulo'),
(12342,'Mario Carmo','2002-07-29','Americana'),
(12343,'Lucio Castro','1969-12-01','Campinas'),
(12344,'André Figueiredo','1999-05-14','São Paulo'),
(12345,'Luiz Carlos','2001-01-09','São Paulo')

CREATE TABLE ONIBUS(
PLACA			CHAR(07)		NOT NULL,
MARCA			VARCHAR(30)		NOT NULL,
ANO				INT				NOT NULL,
DESCRICAO		VARCHAR(20)		NOT NULL
PRIMARY KEY (PLACA)

)
DROP  TABLE ONIBUS
INSERT INTO ONIBUS
VALUES
('adf0965','Mercedes',1999,'Leito'),               
('bhg7654','Mercedes',2002,'Sem Banheiro'),       
('dtr2093','Mercedes',2001,'Ar Condicionado'),     
('gui7625','Volvo',2001,'Ar Condicionado')     

CREATE TABLE VIAGEM(
CODIGO				INT				NOT NULL,
ONIBUS				CHAR(07)		NOT NULL,
MOTORISTA			INT				NOT NULL,
HORAS				VARCHAR(05)		NOT NULL,
HORAC				VARCHAR(05)		NOT NULL,
DESTINO				VARCHAR(30)		NOT NULL
FOREIGN KEY (ONIBUS)
			REFERENCES ONIBUS(PLACA),
FOREIGN KEY (MOTORISTA)
			REFERENCES MOTORISTA(CODIGO)
)
DROP TABLE VIAGEM
INSERT INTO VIAGEM
VALUES
(101,'adf0965',12343,'10h','12h','Campinas'),
(102,'gui7625',12341,'07h','12h','Araraquara'),
(103,'bhg7654',12345,'14h','22h','Rio de Janeiro'),
(104,'dtr2093',12344,'18h','21h','Sorocaba')


--OP1
SELECT 
CASE WHEN (V.HORAS LIKE '%h%')
THEN
LEFT (CONVERT(TIME,SUBSTRING (V.HORAS,1,2)+':00:00',108),5)
END AS CHEGADA,
CASE WHEN (V.HORAC LIKE '%h%')
THEN
LEFT (CONVERT(TIME,SUBSTRING (V.HORAC,1,2)+':00:00',108),5)
END AS SAIDA,
V.DESTINO
FROM VIAGEM V
--OP2
SELECT M.NOME FROM MOTORISTA M
WHERE M.CODIGO IN
(
SELECT V.MOTORISTA FROM VIAGEM V 
WHERE V.DESTINO = 'Sorocaba'
)
--OP3
SELECT DESCRICAO FROM ONIBUS
WHERE PLACA IN (
SELECT V.ONIBUS FROM VIAGEM V 
WHERE V.DESTINO = 'Rio de Janeiro'
)
--OP4
SELECT DESCRICAO,MARCA,ANO FROM ONIBUS
WHERE PLACA IN (
SELECT V.ONIBUS FROM VIAGEM V  INNER JOIN MOTORISTA M
ON  M.CODIGO = V.MOTORISTA
WHERE M.NOME = 'Luiz Carlos'
)
--OP5
SELECT M.NOME,DATEDIFF(YEAR,M.DATN,GETDATE()) AS IDADE,M.NATURALIDADE FROM MOTORISTA M
WHERE DATEDIFF(YEAR,M.DATN,GETDATE()) > 30