--EX.07
USE MASTER
CREATE DATABASE CLIENT_MERC
USE CLIENT_MERC
CREATE TABLE CLIENTES(
RG					VARCHAR(11)			NOT NULL,
CPF					CHAR(11)			NOT NULL,
NOME				VARCHAR(25)			NOT NULL,
LOGRADOURO			VARCHAR(30)			NOT NULL,
NUMERO				INT					NOT NULL
PRIMARY KEY (RG)
)
INSERT INTO CLIENTES
VALUES
('29531844','34519878040','Luiz André','R. Astorga',500),
('13514996x','84984285630','Maria Luiza','R. Piauí',174),
('121985541','23354997310','Ana Barbara','Av. Jaceguai',1141),
('23987746x','43587669920','Marcos Alberto','R. Quinze',22)

CREATE TABLE PEDIDO(
NOTAF				INT					NOT NULL,
VALOR				INT					NOT NULL,
DAT					DATE				NOT NULL,
RG_ClIENTE			VARCHAR(11)			NOT NULL
PRIMARY KEY (NOTAF)
FOREIGN KEY (RG_CLIENTE)
			REFERENCES CLIENTES(RG)
)
INSERT INTO PEDIDO
VALUES
(1001,754,'2018-04-01','121985541'),
(1002,350,'2018-04-02','121985541'),
(1003,30,'2018-04-02','29531844'),
(1004,1500,'2018-04-03','13514996x')

CREATE TABLE MERCADORIA(
CODIGO				INT					NOT NULL,
DESCRICAO			VARCHAR(40)			NOT NULL,
PRECO				INT					NOT NULL,
QTD					INT					NOT NULL,
COD_FORNECEDOR		INT					NOT NULL
PRIMARY KEY (CODIGO)
FOREIGN KEY (COD_FORNECEDOR)
			REFERENCES FORNECEDORES (CODIGO)
)
INSERT INTO MERCADORIA
VALUES
(10,'Mouse,',24,30,1),
(11,'Teclado',50,20,1),
(12,'Cx. De Som',30,8,2),
(13,'Monitor 17',350,4,3),
(14,'Notebook',1500,7,4)

CREATE TABLE FORNECEDORES(
CODIGO				INT					NOT NULL,
NOME				VARCHAR(20)			NOT NULL,
LOGRADOURO			VARCHAR(45)			NOT NULL,
NUMERO				INT					NULL,
PAIS				VARCHAR(05)			NOT NULL,
AREA				INT					NOT NULL,
TELEFONE			VARCHAR(10)			NULL,
CNPJ				CHAR(13)			NULL,
CIDADE				VARCHAR(25)			NULL,
TRANSPORTE			VARCHAR(15)			NULL,
MOEDA				VARCHAR(04)			NOT NULL
PRIMARY KEY (CODIGO)
)
INSERT INTO FORNECEDORES
VALUES
(1,'Clone','Av. Nações Unidas, 12000',12000,'BR',55,'1141487000',NULL,'São Paulo',NULL,'R$'),
(2,'Logitech','28th Street, 100',100,'USA',1,'2127695100',NULL,NULL,'Avião','US$'),
(3,'LG','Rod. Castello Branco',NULL,'BR',55,'800664400','4159978100001','Sorocaba',NULL,'R$'),
(4,'PcChips','Ponte da Amizade',NULL,'PY',595,NULL,NULL,NULL,'Navio','US$')

--OP1
SELECT P.VALOR*0.10 FROM PEDIDO P
WHERE P.NOTAF = 1001
--OP2
SELECT P.VALOR*0.05 FROM PEDIDO P
WHERE P.NOTAF > 700
--OP3
UPDATE MERCADORIA
SET PRECO = PRECO+(PRECO*0.2) 
WHERE QTD < 10
--OP4
SELECT P.DAT,P.VALOR FROM PEDIDO P
INNER JOIN CLIENTES C ON C.RG = P.RG_ClIENTE
WHERE C.NOME LIKE '%Luiz%'
--OP5
SELECT SUBSTRING(C.CPF,1,3)+'.'+ SUBSTRING(C.CPF,4,3)+'.'+ SUBSTRING(C.CPF,7,3)+'-'+
 SUBSTRING(C.CPF,10,2) AS CPF,

 C.LOGRADOURO+' '+CONVERT(VARCHAR(05),C.NUMERO) AS ENDERECO

FROM CLIENTES C INNER JOIN PEDIDO P 
ON P.RG_ClIENTE = C.RG
WHERE P.NOTAF = 1004
--OP6
SELECT F.PAIS,F.TRANSPORTE FROM MERCADORIA M
INNER JOIN FORNECEDORES F ON F.CODIGO = M.COD_FORNECEDOR
WHERE M.DESCRICAO = 'Cx. De som'
--OP7
SELECT M.DESCRICAO,SUM(M.QTD) FROM 
FORNECEDORES F 
INNER JOIN MERCADORIA M
ON M.COD_FORNECEDOR = F.CODIGO
WHERE F.NOME = 'Clone'
GROUP BY M.DESCRICAO
--OP8
SELECT F.LOGRADOURO+' '+
CASE WHEN (F.NUMERO IS NULL)
THEN
CAST(F.NUMERO AS VARCHAR(05))
ELSE
''
END
+' '+
F.CIDADE+' '+F.PAIS,

CASE WHEN (F.TELEFONE LIKE '800%')
THEN
	'('+SUBSTRING(F.TELEFONE,1,2)+')'+SUBSTRING(F.TELEFONE,3,4)+'-'+SUBSTRING(F.TELEFONE,7,4)
ELSE
	'('+SUBSTRING(F.TELEFONE,1,3)+')'+SUBSTRING(F.TELEFONE,4,3)+'-'+SUBSTRING(F.TELEFONE,7,4)
END AS TELEFONE
FROM FORNECEDORES F INNER JOIN MERCADORIA M ON M.COD_FORNECEDOR = F.CODIGO
WHERE M.DESCRICAO LIKE '%monitor%'
--OP9
SELECT F.MOEDA FROM FORNECEDORES F INNER JOIN MERCADORIA M
ON M.COD_FORNECEDOR = F.CODIGO
WHERE M.DESCRICAO  = 'notebook'
--OP10
SELECT 
DATEDIFF(DAY,P.DAT,'2019-02-03'),
CASE WHEN (DATEDIFF(MONTH,P.DAT,'2019-02-03') > 6)
THEN
'Pedido antigo'
ELSE
'Pedido recente'
END
FROM PEDIDO P
--OP11
SELECT C.NOME,COUNT(P.RG_ClIENTE) FROM CLIENTES C INNER JOIN PEDIDO P
ON P.RG_ClIENTE = C.RG
GROUP BY C.NOME
--OP12
SELECT C.RG,
SUBSTRING(C.CPF,1,3)+'.'+ SUBSTRING(C.CPF,4,3)+'.'+ SUBSTRING(C.CPF,7,3)+'-'+
 SUBSTRING(C.CPF,10,2) AS CPF,
C.NOME,
 C.LOGRADOURO+' '+CONVERT(VARCHAR(05),C.NUMERO) AS ENDERECO
FROM CLIENTES C LEFT OUTER JOIN
PEDIDO P ON P.RG_ClIENTE = C.RG
WHERE P.RG_ClIENTE IS NULL